!noconstruct theme_vars: &tvars
  # --- Input Marker Colors (used in SVG files) ---
  input_main_marker_color: &input_main "#0000ff" # blue
  input_secondary_marker_color: &input_sec "#00ff00" # green

  # --- Output Theme Colors ---
  fluo_colors: &fcolors
    red: { dark: "#840137", base: "#ef957d", light: "#ffe5de", "bright": "#FF2C4944" }
    green: { dark: "#0e633a", base: "#6ccb83", light: "#efffdd", "bright": "#0EFF7377" }
    blue: { dark: "#006394", base: "#6cafc3", light: "#f3fafd", "bright": "#1AD5FF60" }
    yellow: { dark: "#9b6600", base: "#fad26d", light: "#fff888", "bright": "#FFC83Caa" }
    ir: { dark: "#6c1772", base: "#df9ae4", light: "#ffe7f4", "bright": "#FF82FCaa" }
    maroon: { dark: "#734727", base: "#d3a888", light: "#f4decd", "bright": "#FF9853a0" }

  marker_colors: &marker_colors # define alias for easier reference below
    EYFPG5A: *fcolors@yellow
    EYFP: *fcolors@yellow
    NEONGREEN: *fcolors@green
    EGFP: *fcolors@green
    EMGFP: *fcolors@green
    TAGGFP: *fcolors@green
    TAGBFP2: *fcolors@green
    MNG: *fcolors@green
    MNEONGREEN: *fcolors@green
    L0_G_MNEONGREEN: *fcolors@green
    EBFP: *fcolors@blue
    EBFP2: *fcolors@blue
    TAGBFP: *fcolors@blue
    SIRIUS: *fcolors@blue
    MKATE: *fcolors@red
    MKATE2: *fcolors@red
    MKO: *fcolors@red
    MKO2: *fcolors@red
    MORANGE: *fcolors@red
    TDTOMATO: *fcolors@red
    IRFP720: *fcolors@ir
    1XIRFP720: *fcolors@ir
    L0_G_IRFPMYSTERY: *fcolors@ir
    IRFP: *fcolors@ir
    MMAROON: *fcolors@maroon
    MMAROON1: *fcolors@maroon
    MPLUM: *fcolors@maroon

  ern_colors: &ern_colors # define alias
    CSY4: "#aaaaaa"
    CASE: "#cccccc"
    PGU: "#eeeeee"

  border_color: &border_color "#222"
  text_color: &text_color "#222"
  ern_interaction_color: &ern_int_color "#555" # used for connection color
  comp_connection_color: &comp_conn_color "#222" # used for connection color


!define theme: ${construct(&tvars)}

# --- Genetic Schematic Styles ---

GeneticPart:
  SVGElement:
    color_remap:
      "${theme.input_main_marker_color}": "#aaaaaa"
      "${theme.input_secondary_marker_color}": *border_color
  Text:
    color: *text_color
    align: center
    font_size: 6
    offset: !Offset
      reference_relative: [0.5, 0.5]
      relative: [-0.5, -0.5]

Promoter:
  offset: !Offset
    relative: [0, 0.5]
    absolute: [-0.5, 0]

Terminator:
  offset: !Offset
    relative: [0.5, 0.5]
  style.margin: [0, 0, 0, -10]

ERN:
  layout.direction: row
  Text:
    align: center
    vertical_align: middle
    font_size: 9
    z_index: 10
    offset.absolute: [-8, 0]

ERN5pRecog:
  offset: !Offset
    relative: [0, 0.4]
    absolute: [0, 0.5]
  style.margin: [0, 2, 0, -4]

UorfGroup:
  style.margin: [0, 0, 0, -4]
  offset: !Offset
    relative: [0, 0.1]
  Text:
    offset.absolute: [0, -8]


!each(e) ${theme.marker_colors.items()}: # Loop through marker types
  FluoMarker[part_name=~${e[0]}]:
    SVGElement:
      color_remap:
        ${theme.input_main_marker_color}: ${e[1]['light']}
        ${theme.input_secondary_marker_color}: ${e[1]['base']}
    Text:
      color: ${e[1]['dark']}
      offset.absolute: [-2, 0]


  SourceAnnotation[marker=~${e[0]}]:
    style.border_color: ${e[1]['base']}
    Container[style_class=source_tag]: # Target the nested tag container
      style.background_color: ${e[1]['light']}
      style.border_color: ${e[1]['dark']}
      SVGElement:
        color_remap:
           ${theme.input_main_marker_color}: ${e[1]['dark']}
      Text:
        color: ${e[1]['dark']}

TranscriptionUnit:
  line_thickness: 1
  line_color: *border_color
  layout.gap: 4
  Text: # TU Label
    color: "#999"
    font_size: 5
    offset: !Offset
      reference_relative: [0, 1.3]

SourceAnnotation:
  style.padding: [18, 18, 20, 18]
  style.margin: [4, 4, 4, 4]
  style.border_color: *border_color
  style.border_width: 1
  style.corner_radius: 5
  style.border_style: custom
  style.dash_sequence: [3, 4]

Container[style_class=source_tag]:
  style.background_color: "#dddddd"
  style.border_color: *border_color
  style.border_width: 0.5
  style.corner_radius: 50
  style.padding: [3, 5, 3, 2]
  offset: !Offset
    relative: [0, -0.5]
    absolute: [10, 0]
  layout.direction: row
  layout.align_items: center
  layout.justify_content: start
  layout.gap: 3
  SVGElement:
    offset: !Offset { relative: [0, 0] }
    style.margin: [0, 0, 0, 3]
    color_remap:
      ${theme.input_main_marker_color}: *border_color
  Text:
    color: *text_color
    font_size: 6

"[source_type=plasmid]":
  Container[style_class=source_tag]:
    SVGElement:
      transform.scale: [0.7, 0.7]

"[source_type=cotx]":
  Container[style_class=source_tag]:
    SVGElement:
      transform.scale: [0.9, 0.9]

NetworkGeneticSchematic:
  grid_gap: [50, 50]
  style.padding: [5,5,5,5]

# Schematic Anchor Points
"[style_class=ern-anchor-top]":
  offset.reference_relative: [0.77, 1.1]
  min_segment: 25

"[style_class=ern-anchor-bottom]":
  offset.reference_relative: [0.77, -0.1]
  min_segment: 12

"[style_class=ern-recog-anchor-top]":
  offset.reference_relative: [0.5, 1.1]
  min_segment: 15

"[style_class=ern-recog-anchor-bottom]":
  offset.reference_relative: [0.5, -0.2] 
  min_segment: 5



!each(e) ${theme.ern_colors.items()}: # Loop through ERN types (CSY4, CASE, etc.)
  "ERN[part_name=~${e[0]}]": # Style ERN based on part name
    SVGElement:
      color_remap:
        ${theme.input_main_marker_color}: ${e[1]}


!each(e) ${enumerate(theme.ern_colors.items())}:
  ERN5pRecog[part_name=~${e[1][0]}_rec]:
    SVGElement:
      color_remap:
        ${theme.input_main_marker_color}: ${e[1][1]}



# --- Network Diagram Styles ---



FluoNode:
  style.border_color: "#00000030"
  style.background_color: "#FFBB79"
  style.shadow: !Shadow { color: "#FF8006", blur_radius: 15, resolution: 0.01, z_index: 1 }

!each(e) ${theme.marker_colors.items() }:
  FluoNode[style_class=~${e[0]}]:
    style.background_color: ${e[1]['light']}
    style.shadow: !Shadow { color: "${e[1]['bright']}", blur_radius: 15, resolution: 0.01, z_index: 1 }
    Text:
      color: ${e[1]['dark']}
      font_size: 8
      vertical_align: middle
      align: center

  AggregationNode[style_class=~${e[0]}]:
    style.background_color: ${e[1]['light']}
  #   style.shadow: !Shadow { color: "${e[1]['bright']}", blur_radius: 15, resolution: 0.01 }
    Text:
      color: "#222" 
      font_size: 6    
      vertical_align: middle
      align: center
      offset: !Offset { relative: [0, 2] }  # Offset down a bit

  TUNode[style_class=~${e[0]}]:
    # style.background_color: ${e[1]['light']}
    style.shadow: !Shadow { color: "${e[1]['bright']}", blur_radius: 15, resolution: 0.01 }
    Text:
      color: ${e[1]['dark']}
      font_size: 6
      vertical_align: middle
      align: center

  Text[style_class=tu_label_marker][style_class=~${e[0]}]:
    color: ${e[1]['dark']}


ComputeNode:
  min_dimensions: !Size { width: 18, height: 18 }
  style.corner_radius: 1.0e+6 # Circle
  style.background_color: "#aaa"
  style.border_color: ${theme.comp_connection_color}
  style.border_width: 1
  style.margin: [10, 10, 10, 10]
  layout.align_items: center
  layout.justify_content: center
  Text:
    font_size: 7
    color: "#fff"
    vertical_align: middle
    align: center

TranscriptionNode:
  style.background_color: "#555"

TranslationNode:
  style.background_color: "#333"

InputNode:
  style.background_color: "#222"
  Text:
    color: "#fff"

BiasNode:
  style.background_color: "#bbb"
  Text:
    color: "#444"

ERNNode:
  min_dimensions: !Size { width: 70, height: 70 }
  max_dimensions: !Size { width: 70, height: 70 }
  style.background_color: "#eee"
  style.border_style: custom
  style.dash_sequence: [5, 5]
  style.border_width: 1
  TranslationNode: # Nested rule for Tl node inside ERNNode
    style.background_color: "#ee3350"
    offset: !Offset { reference_relative: [0, 0.9], relative: [0, -1] }
  TranscriptionNode: # Nested rule for Tx node inside ERNNode
    offset: !Offset { reference_relative: [0, 0.1] }
  Connection[style_class=tlconn]: # Nested rule for TL connection inside ERNNode
    color: "#ee3350"
    line_width: 1
    start_offset: !Offset { relative: [1, 0.5] }
    end_offset: !Offset { absolute: [15, 3] }
    curve_type.start_direction: right
    curve_type.end_direction: up
    curve_type.start_length: 5
    curve_type.end_length: 5
    curve_type.corner_radius: 10
    z_index: -1
    end_cap.stroke_color: "#ee3350"
    end_cap.stroke_width: 1
    end_cap.length: 8
  Connection[style_class=txconn]:
    color: ${theme.comp_connection_color}
    line_width: 1
    z_index: -1
    curve_type.start_mode: vector
    curve_type.end_mode: vector
    curve_type.start_vector: [15, 15]
    curve_type.end_vector: [-40, 0]
    start_offset: !Offset { relative: [0.9, 0.8] }
  Text[style_class=ern_name]:
    color: "#888"
    font_size: 8
    vertical_align: middle
    align: center
    offset: !Offset { reference_relative: [0.5, 0.1], relative: [-0.5, 0] }
    is_overlay: true


InvNode: # Diagram node
  style.background_color: "#eee"
  style.border_color: "#111"
  Text:
    color: *text_color # use theme text color

TUNode: # Diagram node (small bar)
  min_dimensions: !Size { width: 15, height: 4 }
  max_dimensions: !Size { width: 15, height: 4 } # ensure it stays small
  style.background_color: "#111"
  style.border_width: 0
  style.margin: [0, 0, 0, 0]
  offset: !Offset {}
  Text:
    color: "#000000"
    vertical_align: middle
    align: right
    is_overlay: true
    offset: !Offset { reference_relative: [0, 0], absolute: [-10, 0], relative: [-1, -0.3] }
  Container[style_class=tu_label_container]:
    offset: !Offset { reference_relative: [0, 0], absolute: [-10, 0], relative: [-1, -0.3] }
    Text[style_class=tu_label_prefix]:
      color: "#000000"
      font_size: 6
      vertical_align: middle
    Text[style_class=tu_label_suffix]:
      color: "#000000"
      font_size: 6
      vertical_align: middle
    Text[style_class=tu_label_marker]:
      font_size: 6
      vertical_align: middle


# AggregationNode: # Base style for aggregation node container
#   style.shadow: !Shadow { color: "#FFA068aa", blur_radius: 15, resolution: 1 }

AggregationNode[!collapsed]: # Expanded aggregation node
  style.background_color: "#FFFFFFAA"
  style.border_color: "#FFA068"
  style.border_width: 1.5
  style.padding: [12, 4, 12, 4]
  layout: !LayoutConstraints { direction: column, justify_content: space-around, gap: 5 }
  TUNode:
    is_overlay: false


AggregationNode[collapsed]: # Collapsed aggregation node
  min_dimensions: !Size { width: 15, height: 4 }
  max_dimensions: !Size { width: 15, height: 4 }
  style.border_width: 0
  style.padding: [0, 0, 0, 0]
  # style.shadow: !Shadow { color: "#FFA068", blur_radius: 20, resolution: 0.1 }


  TUNode:
    is_overlay: true
    offset: !Offset { absolute: [0, 0] }

AggregationNode[collapsed][bias_connected]: # Bias-connected collapsed aggregation (grey instead of black)
  TUNode:
    style.background_color: "#999"

Container[style_class=input_layer]:
  style.padding: [0, 0, 0, 40]

DeadEndNode: # no border, no shadow
  style.background_color: "#00000000"
  style.border_width: 0
  style.padding: [0, 0, 0, 0]
  Text:
    color: "#000000"
    font_size: 12
    vertical_align: middle
    align: center

Connection[style_class=connection_ERN]:
  line_width: 0.5
  color: *ern_int_color
  end_cap.stroke_color: *ern_int_color # Match end cap color
  end_cap.stroke_width: 0.5
  end_cap.length: 8



Table:
  TableCell:
    style.padding: [7, 10, 7, 10]
    style.border_color: *border_color
    style.border_width: 0.5
    Text:
      align: center
      vertical_align: middle
  TableCell[style_class=table-header-cell]:
    style.background_color: "#eee"
    Text:
      font_weight: bold

!noconstruct _network_diagram_base: &nd_base
  layout.gap: 25
  layout.direction: row
  layout.align_items: center
  layout.justify_content: center

  Connection[style_class=comp-connection]:
    color: ${theme.comp_connection_color}
    line_width: 1
    start_offset: !Offset { reference_relative: [0.99, 0.5] }
    end_offset: !Offset { reference_relative: [0.0, 0.5], absolute: [0, 0] }
    curve_type: !SimpleBezierCurve
      start_mode: vector
      end_mode: vector
      start_vector: [20, 0]
      end_vector: [-15, 0]
    end_cap: !LineEndCircle
      fill_color: ${theme.comp_connection_color}
      stroke_width: 0
      radius: 1.5
      z-index: 10

  Connection[style_class=dst-deadend]:
    end_offset: !Offset { reference_relative: [0.5, 0.5] }

  Connection[style_class=dst-source]:
    end_offset: !Offset { reference_relative: [0.5, 0.5] }
    curve_type: !StraightCurve {}

  Container[style_class=layer]:
    layout.gap: 10
    layout.direction: column
    layout.align_items: center
    layout.justify_content: center

  Container[style_class=input_layer]:
    layout.gap: 15

  Container[style_class=auto_layer]:
    style.padding: [0, 0, 0, 0]

  Container[style_class=output_layer]:
    style.padding: [0, 0, 0, 20]

  Container[style_class=main_layer]:
    layout.direction: column
    layout.align_items: center
    layout.justify_content: center
    style.margin: [0, 0, 0, 0]
    layout.gap: 20

  Text[style_class=layer_title]:
    color: "#777"
    font_size: 7

NetworkDiagram:
  <<: *nd_base

NetworkDiagramV2:
  <<: *nd_base
