"""Introspect the cascade-selectable surface: every selectable type, its *own* stylable
fields + defaults. Powers `resources/themes/defaults.yaml` (the override floor every theme
layers on) and discovery (`python -m jeanplot.style_schema [Type ...]`).

Own-fields-only keeps it DRY: a `Component:` rule already matches every subtype via MRO, so
each type lists only the fields it introduces. Non-serializable defaults (arrays, sub-models,
rescalers) are skipped -- the curated themes own those."""

import sys
from typing import Any

import yaml
from pydantic import BaseModel
from pydantic_core import PydanticUndefined

from jeanplot import DEFAULT_TYPES

# data inputs / tree wiring / runtime state -- never a style knob. `attached_to` is
# excluded: it is now a theme-owned float target (see common/theme.yaml metric-cell).
_SKIP = {
    "parent",
    "anchor_points",
    "attachment_offset",
    "renderer_options",
    "plot_data",
    "contour_reference_plot_data",
}


def _serializable(v: Any) -> bool:
    if v is None or isinstance(v, (bool, int, float, str)):
        return True
    if isinstance(v, (list, tuple)):
        return all(_serializable(x) for x in v)
    if isinstance(v, dict):
        return all(isinstance(k, str) and _serializable(x) for k, x in v.items())
    return False


def _default(field) -> Any:
    if field.default is not PydanticUndefined:
        return field.default
    if field.default_factory is not None:
        try:
            return field.default_factory()  # pyright: ignore[reportCallIssue]
        except Exception:
            return PydanticUndefined
    return PydanticUndefined


def own_stylable_fields(cls: type[BaseModel]) -> dict[str, Any]:
    """Fields `cls` introduces (not inherited) whose default is YAML-serializable."""
    inherited: set[str] = set()
    for base in cls.__mro__[1:]:
        if issubclass(base, BaseModel) and base is not cls:
            inherited |= set(base.model_fields)
    out: dict[str, Any] = {}
    for name, field in cls.model_fields.items():
        if name in inherited or name in _SKIP or name.startswith("_"):
            continue
        d = _default(field)
        if d is PydanticUndefined or not _serializable(d):
            continue
        out[name] = list(d) if isinstance(d, tuple) else d
    return out


def schema_tree(types: list[type] = DEFAULT_TYPES) -> dict[str, dict[str, Any]]:
    tree: dict[str, dict[str, Any]] = {}
    for cls in types:
        if not (isinstance(cls, type) and issubclass(cls, BaseModel)):
            continue
        fields = own_stylable_fields(cls)
        if fields:
            tree[cls.__name__] = fields
    return tree


_HEADER = """\
# GENERATED by `python -m jeanplot.style_schema` -- do not edit by hand; regenerate after
# adding a selectable type or field.
#
# This is the BASE THEME WITH EVERYTHING IN IT: every selectable type's own stylable fields
# at their pydantic defaults, as one `!cascade:jstyle_fill`. Two uses:
#
#   1. Discovery -- the single place to see every knob you can override and its default.
#      `python -m jeanplot.style_schema [Type ...]` prints it (no args = the whole floor).
#
#   2. A base for a NEW flat-rule theme -- include `@_body` first, then layer overrides:
#        rules: !cascade:jstyle_fill
#          <<: !include pkg:jeanplot:resources/themes/defaults.yaml@_body
#          <<{+<}:
#            SmoothPanel2D:
#              vlims: [0.0, 1.0]
#
# NOT auto-wired under the curated themes (default.yaml / paper.yaml). Its bare type rules
# (e.g. `SVGElement:`) are LESS specific than the descendant rules those themes rely on
# (`GeneticPart SVGElement:`), so layering it underneath shifts specificity and changes
# their output. It is a reference + a base for new flat-rule themes, not a universal underlay.
"""


def render_defaults_yaml(types: list[type] = DEFAULT_TYPES) -> str:
    body = yaml.safe_dump(schema_tree(types), sort_keys=True, default_flow_style=False, indent=2)
    indented = "".join("  " + line if line.strip() else line for line in body.splitlines(True))
    return f"{_HEADER}\n_body:\n{indented}\nrules: !cascade:jstyle_fill\n  <<: ${{&/_body}}\n"


def main(argv: list[str] | None = None) -> None:
    args = sys.argv[1:] if argv is None else argv
    tree = schema_tree()
    if args:
        wanted = set(args)
        tree = {k: v for k, v in tree.items() if k in wanted}
        print(yaml.safe_dump(tree, sort_keys=True, default_flow_style=False, indent=2), end="")
    else:
        print(render_defaults_yaml(), end="")


if __name__ == "__main__":
    main()
